# This template demonstrates a workflow of workflows.
# Workflow triggers one or more workflow and manage it.
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-multi-ns-
spec:
  entrypoint: main
  serviceAccountName: argo
  templates:
    - name: main
      steps:
        - - name: workflow1
            template: triggerWorkflow
            arguments:
              parameters:
                - name: namespace
                  value: "{{item}}"
            withItems:
              - default
              - argo
    - name: triggerWorkflow
      inputs:
        parameters:
          - name: namespace
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-1-
            namespace: {{inputs.parameters.namespace}}
          spec:
            entrypoint: whalesay
            serviceAccountName: default
            templates:
              - name: whalesay
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["hello world {{inputs.parameters.namespace}}"]
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
